/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3d/north_beach_web.glb --output src/components/NorthBeachGenerated.tsx --types --keepgroups 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'clouds_floating.016Action' | 'Cylinder.006Action' | 'top_capAction'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Terrain: THREE.Mesh
    coit_base: THREE.Mesh
    water: THREE.Mesh
    clouds_city: THREE.Mesh
    clouds_water034: THREE.Mesh
    clouds_floating016: THREE.Mesh
    buildings003: THREE.Mesh
    buildings001: THREE.Mesh
    buildings005: THREE.Mesh
    buildings: THREE.Mesh
    buildings007: THREE.Mesh
    Cylinder006: THREE.Mesh
    top_cap: THREE.Mesh
  }
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial
    e0e0e0: THREE.MeshStandardMaterial
    water: THREE.MeshStandardMaterial
    white_100: THREE.MeshStandardMaterial
    foggy_blue: THREE.MeshStandardMaterial
    sunset_peach: THREE.MeshStandardMaterial
    seafoam_green: THREE.MeshStandardMaterial
    golden_sand: THREE.MeshStandardMaterial
    lavender_mist: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: React.ComponentProps<'group'>) {
  const group = React.useRef<THREE.Group>(null!)
  const { nodes, materials, animations } = useGLTF('/3d/north_beach_web.glb') as unknown as GLTFResult
  useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Terrain" geometry={nodes.Terrain.geometry} material={materials['Material.002']} position={[0.418, -3.521, -0.327]} scale={0.014} />
        <mesh name="coit_base" geometry={nodes.coit_base.geometry} material={materials.e0e0e0} position={[-0.003, -1.424, 0.018]} scale={0.436} />
        <mesh name="water" geometry={nodes.water.geometry} material={materials.water} />
        <mesh name="clouds_city" geometry={nodes.clouds_city.geometry} material={materials.white_100} position={[-7.612, -2.829, -8.723]} scale={2.122} />
        <mesh name="clouds_water034" geometry={nodes.clouds_water034.geometry} material={materials.white_100} position={[16.638, -3.525, -1.033]} rotation={[-2.91, 0.936, 2.983]} scale={2.636} />
        <mesh name="clouds_floating016" geometry={nodes.clouds_floating016.geometry} material={materials.white_100} />
        <mesh name="buildings003" geometry={nodes.buildings003.geometry} material={materials.foggy_blue} position={[0.418, -3.521, -0.327]} scale={0.014} />
        <mesh name="buildings001" geometry={nodes.buildings001.geometry} material={materials.sunset_peach} position={[0.418, -3.521, -0.327]} scale={0.014} />
        <mesh name="buildings005" geometry={nodes.buildings005.geometry} material={materials.seafoam_green} position={[0.418, -3.521, -0.327]} scale={0.014} />
        <mesh name="buildings" geometry={nodes.buildings.geometry} material={materials.golden_sand} position={[0.418, -3.521, -0.327]} scale={0.014} />
        <mesh name="buildings007" geometry={nodes.buildings007.geometry} material={materials.lavender_mist} position={[0.418, -3.521, -0.327]} scale={0.014} />
        <mesh name="Cylinder006" geometry={nodes.Cylinder006.geometry} material={materials.white_100} position={[0.006, -0.996, -0.024]} scale={17.756} />
        <mesh name="top_cap" geometry={nodes.top_cap.geometry} material={materials.white_100} position={[0.006, 0.487, -0.023]} />
      </group>
    </group>
  )
}

useGLTF.preload('/3d/north_beach_web.glb')
