/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/narfa/_git/hotdrops/public/3d/north_beach_web.glb --output /home/narfa/_git/hotdrops/src/components/NorthBeachGenerated.tsx --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'topAction'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Terrain: THREE.Mesh
    top: THREE.Mesh
    bottom: THREE.Mesh
    base: THREE.Mesh
    Cylinder: THREE.Mesh
    roofs: THREE.Mesh
    Icosphere: THREE.Mesh
    Icosphere001: THREE.Mesh
    Icosphere002: THREE.Mesh
    Icosphere003: THREE.Mesh
    Icosphere004: THREE.Mesh
    Icosphere005: THREE.Mesh
    Icosphere006: THREE.Mesh
    Icosphere007: THREE.Mesh
    Icosphere008: THREE.Mesh
    Icosphere009: THREE.Mesh
    Icosphere010: THREE.Mesh
    Icosphere011: THREE.Mesh
    Icosphere015: THREE.Mesh
    Icosphere016: THREE.Mesh
    Icosphere017: THREE.Mesh
    Icosphere018: THREE.Mesh
    Icosphere019: THREE.Mesh
    Icosphere020: THREE.Mesh
    Icosphere027: THREE.Mesh
    Icosphere028: THREE.Mesh
    Icosphere029: THREE.Mesh
    Icosphere030: THREE.Mesh
    Icosphere031: THREE.Mesh
    Icosphere032: THREE.Mesh
    Icosphere033: THREE.Mesh
    Icosphere034: THREE.Mesh
    Icosphere035: THREE.Mesh
    Icosphere036: THREE.Mesh
    Icosphere037: THREE.Mesh
    Icosphere038: THREE.Mesh
    Icosphere013: THREE.Mesh
    Icosphere014: THREE.Mesh
    Icosphere021: THREE.Mesh
    Icosphere022: THREE.Mesh
    Icosphere025: THREE.Mesh
    Icosphere026: THREE.Mesh
    Icosphere039: THREE.Mesh
    Icosphere040: THREE.Mesh
    Icosphere041: THREE.Mesh
    Icosphere042: THREE.Mesh
    Icosphere043: THREE.Mesh
    Icosphere044: THREE.Mesh
    Icosphere045: THREE.Mesh
    Icosphere046: THREE.Mesh
    Icosphere047: THREE.Mesh
    Icosphere048: THREE.Mesh
    Icosphere049: THREE.Mesh
    Icosphere050: THREE.Mesh
    Icosphere051: THREE.Mesh
    Icosphere052: THREE.Mesh
    Icosphere012: THREE.Mesh
    Icosphere023: THREE.Mesh
    Icosphere024: THREE.Mesh
    Icosphere053: THREE.Mesh
    Icosphere054: THREE.Mesh
    Icosphere055: THREE.Mesh
    Icosphere056: THREE.Mesh
    Icosphere057: THREE.Mesh
    Icosphere058: THREE.Mesh
    Icosphere059: THREE.Mesh
    Icosphere060: THREE.Mesh
    Icosphere061: THREE.Mesh
    Icosphere062: THREE.Mesh
    Icosphere063: THREE.Mesh
    Icosphere064: THREE.Mesh
    Icosphere065: THREE.Mesh
    Icosphere066: THREE.Mesh
  }
  materials: {
    roof: THREE.MeshStandardMaterial
    water: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/3d/north_beach_web.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Terrain" geometry={nodes.Terrain.geometry} material={nodes.Terrain.material} position={[0.418, -3.521, -0.327]} scale={0.014} />
        <mesh name="top" geometry={nodes.top.geometry} material={nodes.top.material} position={[0.007, 0.23, -0.022]} scale={13.764} />
        <mesh name="bottom" geometry={nodes.bottom.geometry} material={nodes.bottom.material} position={[0.01, -1.246, -0.033]} rotation={[-Math.PI, -0.011, 0]} scale={[0.067, 0.062, 0.067]} />
        <mesh name="base" geometry={nodes.base.geometry} material={materials.roof} position={[-0.003, -1.424, 0.018]} scale={0.436} />
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials.water} />
        <mesh name="roofs" geometry={nodes.roofs.geometry} material={materials.roof} position={[0.418, -3.521, -0.327]} scale={0.014} />
        <mesh name="Icosphere" geometry={nodes.Icosphere.geometry} material={nodes.Icosphere.material} position={[-7.612, -2.829, -8.723]} scale={2.122} />
        <mesh name="Icosphere001" geometry={nodes.Icosphere001.geometry} material={nodes.Icosphere001.material} position={[-9.115, -4.332, -6.029]} scale={2.927} />
        <mesh name="Icosphere002" geometry={nodes.Icosphere002.geometry} material={nodes.Icosphere002.material} position={[-8.531, -2.741, -0.397]} rotation={[Math.PI, -1.054, Math.PI]} scale={2.37} />
        <mesh name="Icosphere003" geometry={nodes.Icosphere003.geometry} material={nodes.Icosphere003.material} position={[-10.318, -4.419, -3.343]} rotation={[Math.PI, -1.054, Math.PI]} scale={3.269} />
        <mesh name="Icosphere004" geometry={nodes.Icosphere004.geometry} material={nodes.Icosphere004.material} position={[-9.402, -4.419, 3.037]} rotation={[2.254, -1.211, 2.574]} scale={3.733} />
        <mesh name="Icosphere005" geometry={nodes.Icosphere005.geometry} material={nodes.Icosphere005.material} position={[-10.494, -2.941, 6.399]} rotation={[-0.679, 0.717, 1.26]} scale={2.927} />
        <mesh name="Icosphere006" geometry={nodes.Icosphere006.geometry} material={nodes.Icosphere006.material} position={[-8.942, -2.466, 8.856]} rotation={[1.127, -0.553, 1.003]} scale={3.269} />
        <mesh name="Icosphere007" geometry={nodes.Icosphere007.geometry} material={nodes.Icosphere007.material} position={[-5.509, -4.065, 8.691]} rotation={[-Math.PI, 1.419, -Math.PI]} scale={2.927} />
        <mesh name="Icosphere008" geometry={nodes.Icosphere008.geometry} material={nodes.Icosphere008.material} position={[-0.03, -2.475, 9.712]} rotation={[0, -0.365, 0]} scale={2.37} />
        <mesh name="Icosphere009" geometry={nodes.Icosphere009.geometry} material={nodes.Icosphere009.material} position={[-2.671, -4.153, 9.472]} rotation={[0, -0.365, 0]} scale={3.269} />
        <mesh name="Icosphere010" geometry={nodes.Icosphere010.geometry} material={nodes.Icosphere010.material} position={[3.497, -4.153, 10.052]} rotation={[0.277, -0.078, 0.309]} scale={3.733} />
        <mesh name="Icosphere011" geometry={nodes.Icosphere011.geometry} material={nodes.Icosphere011.material} position={[6.986, -2.675, 9.293]} rotation={[-2.572, 0.501, -2.667]} scale={2.927} />
        <mesh name="Icosphere015" geometry={nodes.Icosphere015.geometry} material={nodes.Icosphere015.material} position={[3.846, -2.482, 11.655]} rotation={[Math.PI, -1.381, Math.PI]} scale={3.502} />
        <mesh name="Icosphere016" geometry={nodes.Icosphere016.geometry} material={nodes.Icosphere016.material} position={[-5.321, -1.646, 12.73]} rotation={[-Math.PI, 0.707, -Math.PI]} scale={2.836} />
        <mesh name="Icosphere017" geometry={nodes.Icosphere017.geometry} material={nodes.Icosphere017.material} position={[-1.455, -2.025, 12.719]} rotation={[-Math.PI, 0.707, -Math.PI]} scale={3.911} />
        <mesh name="Icosphere018" geometry={nodes.Icosphere018.geometry} material={nodes.Icosphere018.material} position={[-13.488, -2.464, 1.112]} rotation={[2.079, 1.472, -2.441]} scale={3.911} />
        <mesh name="Icosphere019" geometry={nodes.Icosphere019.geometry} material={nodes.Icosphere019.material} position={[-14.968, -2.285, 6.69]} rotation={[2.079, 1.472, -2.441]} scale={5.064} />
        <mesh name="Icosphere020" geometry={nodes.Icosphere020.geometry} material={nodes.Icosphere020.material} position={[-10.823, 0.321, 13.329]} rotation={[2.201, 0.963, -2.447]} scale={5.064} />
        <mesh name="Icosphere027" geometry={nodes.Icosphere027.geometry} material={nodes.Icosphere027.material} position={[9.696, -4.49, 7.605]} rotation={[0, -0.365, 0]} scale={2.82} />
        <mesh name="Icosphere028" geometry={nodes.Icosphere028.geometry} material={nodes.Icosphere028.material} position={[9.696, -3.522, 5.476]} rotation={[0.15, 0.029, -0.31]} scale={1.194} />
        <mesh name="Icosphere029" geometry={nodes.Icosphere029.geometry} material={nodes.Icosphere029.material} position={[14.971, -4.018, -3.329]} rotation={[Math.PI, -0.359, Math.PI]} scale={1.642} />
        <mesh name="Icosphere030" geometry={nodes.Icosphere030.geometry} material={nodes.Icosphere030.material} position={[13.553, -3.125, -6.172]} rotation={[0, 1.413, 0]} scale={1.33} />
        <mesh name="Icosphere031" geometry={nodes.Icosphere031.geometry} material={nodes.Icosphere031.material} position={[15.073, -4.067, -4.977]} rotation={[0, 1.413, 0]} scale={1.835} />
        <mesh name="Icosphere032" geometry={nodes.Icosphere032.geometry} material={nodes.Icosphere032.material} position={[13.333, -4.067, -8.148]} rotation={[1.988, 1.267, -1.718]} scale={2.095} />
        <mesh name="Icosphere033" geometry={nodes.Icosphere033.geometry} material={nodes.Icosphere033.material} position={[13.243, -3.238, -10.13]} rotation={[-2.163, -0.964, -1.484]} scale={1.642} />
        <mesh name="Icosphere034" geometry={nodes.Icosphere034.geometry} material={nodes.Icosphere034.material} position={[11.943, -2.971, -11.115]} rotation={[2.172, 0.372, -2.486]} scale={1.835} />
        <mesh name="Icosphere035" geometry={nodes.Icosphere035.geometry} material={nodes.Icosphere035.material} position={[10.172, -3.868, -12.286]} rotation={[0, -1.059, 0]} scale={1.642} />
        <mesh name="Icosphere036" geometry={nodes.Icosphere036.geometry} material={nodes.Icosphere036.material} position={[7.092, -2.976, -14.104]} rotation={[-Math.PI, 0.005, -Math.PI]} scale={1.33} />
        <mesh name="Icosphere037" geometry={nodes.Icosphere037.geometry} material={nodes.Icosphere037.material} position={[8.527, -3.918, -12.614]} rotation={[-Math.PI, 0.005, -Math.PI]} scale={1.835} />
        <mesh name="Icosphere038" geometry={nodes.Icosphere038.geometry} material={nodes.Icosphere038.material} position={[5.173, -3.918, -14.889]} rotation={[2.855, -0.268, -2.932]} scale={2.095} />
        <mesh name="Icosphere013" geometry={nodes.Icosphere013.geometry} material={nodes.Icosphere013.material} position={[2.312, -3.54, -14.979]} rotation={[0, -1.506, 0]} scale={1.781} />
        <mesh name="Icosphere014" geometry={nodes.Icosphere014.geometry} material={nodes.Icosphere014.material} position={[-1.085, -2.572, -14.404]} rotation={[-Math.PI, 0.452, -Math.PI]} scale={1.442} />
        <mesh name="Icosphere021" geometry={nodes.Icosphere021.geometry} material={nodes.Icosphere021.material} position={[0.634, -3.594, -15.604]} rotation={[-Math.PI, 0.452, -Math.PI]} scale={1.989} />
        <mesh name="Icosphere022" geometry={nodes.Icosphere022.geometry} material={nodes.Icosphere022.material} position={[-3.205, -3.594, -14.798]} rotation={[2.861, 0.162, -2.808]} scale={2.272} />
        <mesh name="Icosphere025" geometry={nodes.Icosphere025.geometry} material={nodes.Icosphere025.material} position={[-5.289, -2.694, -15.329]} rotation={[-0.598, -0.574, 0.418]} scale={1.781} />
        <mesh name="Icosphere026" geometry={nodes.Icosphere026.geometry} material={nodes.Icosphere026.material} position={[-6.721, -2.405, -14.29]} rotation={[2.148, -0.41, 2.761]} scale={1.989} />
        <mesh name="Icosphere039" geometry={nodes.Icosphere039.geometry} material={nodes.Icosphere039.material} position={[-8.494, -3.378, -12.821]} rotation={[0, 0.217, 0]} scale={1.781} />
        <mesh name="Icosphere040" geometry={nodes.Icosphere040.geometry} material={nodes.Icosphere040.material} position={[-11.35, -2.41, -10.198]} rotation={[Math.PI, -1.271, Math.PI]} scale={1.442} />
        <mesh name="Icosphere041" geometry={nodes.Icosphere041.geometry} material={nodes.Icosphere041.material} position={[-9.352, -3.432, -11.217]} rotation={[Math.PI, -1.271, Math.PI]} scale={1.989} />
        <mesh name="Icosphere042" geometry={nodes.Icosphere042.geometry} material={nodes.Icosphere042.material} position={[-12.77, -3.432, -8.453]} rotation={[1.628, -1.294, 1.917]} scale={2.272} />
        <mesh name="Icosphere043" geometry={nodes.Icosphere043.geometry} material={nodes.Icosphere043.material} position={[8.942, -3.54, 12.503]} rotation={[-Math.PI, 0.69, -Math.PI]} scale={1.781} />
        <mesh name="Icosphere044" geometry={nodes.Icosphere044.geometry} material={nodes.Icosphere044.material} position={[10.85, -2.572, 9.633]} rotation={[0, 0.364, 0]} scale={1.442} />
        <mesh name="Icosphere045" geometry={nodes.Icosphere045.geometry} material={nodes.Icosphere045.material} position={[10.547, -3.594, 11.708]} rotation={[0, 0.364, 0]} scale={1.989} />
        <mesh name="Icosphere046" geometry={nodes.Icosphere046.geometry} material={nodes.Icosphere046.material} position={[12.589, -3.594, 8.359]} rotation={[0.342, 0.619, 0.084]} scale={2.272} />
        <mesh name="Icosphere047" geometry={nodes.Icosphere047.geometry} material={nodes.Icosphere047.material} position={[14.404, -2.694, 7.204]} rotation={[-2.644, -0.134, -2.297]} scale={1.781} />
        <mesh name="Icosphere048" geometry={nodes.Icosphere048.geometry} material={nodes.Icosphere048.material} position={[14.627, -2.405, 5.45]} rotation={[1.503, 0.692, -1.296]} scale={1.989} />
        <mesh name="Icosphere049" geometry={nodes.Icosphere049.geometry} material={nodes.Icosphere049.material} position={[14.772, -3.378, 3.152]} rotation={[Math.PI, -1.033, Math.PI]} scale={1.781} />
        <mesh name="Icosphere050" geometry={nodes.Icosphere050.geometry} material={nodes.Icosphere050.material} position={[14.818, -2.41, -0.726]} rotation={[-Math.PI, 1.055, -Math.PI]} scale={1.442} />
        <mesh name="Icosphere051" geometry={nodes.Icosphere051.geometry} material={nodes.Icosphere051.material} position={[14.191, -3.432, 1.428]} rotation={[-Math.PI, 1.055, -Math.PI]} scale={1.989} />
        <mesh name="Icosphere052" geometry={nodes.Icosphere052.geometry} material={nodes.Icosphere052.material} position={[14.519, -3.432, -2.956]} rotation={[2.765, 0.735, -2.595]} scale={2.272} />
        <mesh name="Icosphere012" geometry={nodes.Icosphere012.geometry} material={nodes.Icosphere012.material} position={[-3.75, 1.96, -5.366]} rotation={[0, -0.121, 0]} scale={-0.565} />
        <mesh name="Icosphere023" geometry={nodes.Icosphere023.geometry} material={nodes.Icosphere023.material} position={[-10.553, 2.403, 2.87]} rotation={[0.319, -0.909, 0.214]} scale={-0.87} />
        <mesh name="Icosphere024" geometry={nodes.Icosphere024.geometry} material={nodes.Icosphere024.material} position={[-5.05, 3.536, 6.087]} rotation={[0.612, 0.433, -3.1]} scale={0.623} />
        <mesh name="Icosphere053" geometry={nodes.Icosphere053.geometry} material={nodes.Icosphere053.material} position={[11.107, 3.536, 6.087]} rotation={[1.949, 0.974, 1.451]} scale={0.531} />
        <mesh name="Icosphere054" geometry={nodes.Icosphere054.geometry} material={nodes.Icosphere054.material} position={[12.17, 2.403, -4.747]} rotation={[-2.796, 0.898, 0.68]} scale={-1.058} />
        <mesh name="Icosphere055" geometry={nodes.Icosphere055.geometry} material={nodes.Icosphere055.material} position={[5.521, 1.96, -10.557]} rotation={[1.775, -0.933, 0.899]} scale={-0.565} />
        <mesh name="Icosphere056" geometry={nodes.Icosphere056.geometry} material={nodes.Icosphere056.material} position={[-0.162, 3.247, 8.369]} rotation={[-0.227, 0.76, 0.094]} scale={-0.565} />
        <mesh name="Icosphere057" geometry={nodes.Icosphere057.geometry} material={nodes.Icosphere057.material} position={[19.267, 7.217, 7.928]} rotation={[-Math.PI, 0.053, -Math.PI]} scale={-0.565} />
        <mesh name="Icosphere058" geometry={nodes.Icosphere058.geometry} material={nodes.Icosphere058.material} position={[25.496, 7.66, -0.749]} rotation={[2.847, 0.845, -2.96]} scale={-0.87} />
        <mesh name="Icosphere059" geometry={nodes.Icosphere059.geometry} material={nodes.Icosphere059.material} position={[19.788, 8.793, -3.587]} rotation={[2.51, -0.488, -0.002]} scale={0.531} />
        <mesh name="Icosphere060" geometry={nodes.Icosphere060.geometry} material={nodes.Icosphere060.material} position={[3.088, 8.001, -16.374]} rotation={[2.126, 0.792, -2.466]} scale={0.531} />
        <mesh name="Icosphere061" geometry={nodes.Icosphere061.geometry} material={nodes.Icosphere061.material} position={[12.277, 9.1, -15.093]} rotation={[1.017, 0.598, -1.152]} scale={-1.058} />
        <mesh name="Icosphere062" geometry={nodes.Icosphere062.geometry} material={nodes.Icosphere062.material} position={[5.095, 11.282, 13.926]} rotation={[0, -1.375, 0]} scale={-0.565} />
        <mesh name="Icosphere063" geometry={nodes.Icosphere063.geometry} material={nodes.Icosphere063.material} position={[-4.85, 11.725, 10.029]} rotation={[2.815, -0.928, 2.835]} scale={-0.87} />
        <mesh name="Icosphere064" geometry={nodes.Icosphere064.geometry} material={nodes.Icosphere064.material} position={[-15.805, 6.103, -3.587]} rotation={[-1.205, -1.098, -0.888]} scale={0.686} />
        <mesh name="Icosphere065" geometry={nodes.Icosphere065.geometry} material={nodes.Icosphere065.material} position={[-1.726, 6.974, 8.353]} rotation={[1.902, 0.445, -2.146]} scale={-1.058} />
        <mesh name="Icosphere066" geometry={nodes.Icosphere066.geometry} material={nodes.Icosphere066.material} position={[-6.728, 8.23, 6.534]} rotation={[-1.864, 0.433, -3.1]} scale={0.623} />
      </group>
    </group>
  )
}

useGLTF.preload('/3d/north_beach_web.glb')
