/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/narfa/_git/hotdrops/public/3d/north_beach_web.glb --output /home/narfa/_git/hotdrops/src/components/NorthBeachGenerated.tsx --types --keepgroups 
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'topAction'

interface GLTFAction extends THREE.AnimationClip {
    name: ActionName
}

type GLTFResult = GLTF & {
    nodes: {
        Terrain: THREE.Mesh
        coit_top: THREE.Mesh
        coit_bottom: THREE.Mesh
        coit_base: THREE.Mesh
        water: THREE.Mesh
        buildings: THREE.Mesh
        clouds_city: THREE.Mesh
        clouds_city001: THREE.Mesh
        clouds_city002: THREE.Mesh
        clouds_city003: THREE.Mesh
        clouds_city004: THREE.Mesh
        clouds_city005: THREE.Mesh
        clouds_city006: THREE.Mesh
        clouds_city007: THREE.Mesh
        clouds_city008: THREE.Mesh
        clouds_city009: THREE.Mesh
        clouds_city010: THREE.Mesh
        clouds_city011: THREE.Mesh
        clouds_city012: THREE.Mesh
        clouds_city013: THREE.Mesh
        clouds_city014: THREE.Mesh
        clouds_city015: THREE.Mesh
        clouds_city016: THREE.Mesh
        clouds_city017: THREE.Mesh
        clouds_city018: THREE.Mesh
        clouds_city019: THREE.Mesh
        clouds_water007: THREE.Mesh
        clouds_water008: THREE.Mesh
        clouds_water009: THREE.Mesh
        clouds_water010: THREE.Mesh
        clouds_water011: THREE.Mesh
        clouds_water012: THREE.Mesh
        clouds_water013: THREE.Mesh
        clouds_water014: THREE.Mesh
        clouds_water015: THREE.Mesh
        clouds_water016: THREE.Mesh
        clouds_water001: THREE.Mesh
        clouds_water002: THREE.Mesh
        clouds_water003: THREE.Mesh
        clouds_water004: THREE.Mesh
        clouds_water005: THREE.Mesh
        clouds_water006: THREE.Mesh
        clouds_water017: THREE.Mesh
        clouds_water018: THREE.Mesh
        clouds_water019: THREE.Mesh
        clouds_water020: THREE.Mesh
        clouds_water021: THREE.Mesh
        clouds_water022: THREE.Mesh
        clouds_water023: THREE.Mesh
        clouds_water024: THREE.Mesh
        clouds_water025: THREE.Mesh
        clouds_water026: THREE.Mesh
        clouds_water027: THREE.Mesh
        clouds_water028: THREE.Mesh
        clouds_water029: THREE.Mesh
        clouds_water: THREE.Mesh
        clouds_floating: THREE.Mesh
        clouds_floating001: THREE.Mesh
        clouds_floating002: THREE.Mesh
        clouds_floating003: THREE.Mesh
        clouds_floating004: THREE.Mesh
        clouds_floating005: THREE.Mesh
        clouds_floating006: THREE.Mesh
        clouds_floating007: THREE.Mesh
        clouds_floating008: THREE.Mesh
        clouds_floating009: THREE.Mesh
        clouds_floating010: THREE.Mesh
        clouds_floating011: THREE.Mesh
        clouds_floating012: THREE.Mesh
        clouds_floating013: THREE.Mesh
        clouds_floating014: THREE.Mesh
        clouds_floating015: THREE.Mesh
        clouds_floating016: THREE.Mesh
    }
    materials: {
        roof: THREE.MeshStandardMaterial
        water: THREE.MeshStandardMaterial
    }
    animations: GLTFAction[]
}

export const Model = React.forwardRef<THREE.Group, JSX.IntrinsicElements['group']>((props, ref) => {
    const group = React.useRef<THREE.Group>(null)
    const { nodes, materials } = useGLTF('/3d/north_beach_web.glb') as unknown as GLTFResult
    return (
        <group ref={ref || group} {...props} dispose={null}>
            <group name="Scene">
                <mesh name="Terrain" geometry={nodes.Terrain.geometry} material={nodes.Terrain.material} position={[0.418, -3.521, -0.327]} scale={0.014} castShadow receiveShadow />
                <mesh name="coit_top" geometry={nodes.coit_top.geometry} material={nodes.coit_top.material} position={[0.007, 0.23, -0.022]} scale={13.764} castShadow receiveShadow />
                <mesh name="coit_bottom" geometry={nodes.coit_bottom.geometry} material={nodes.coit_bottom.material} position={[0.01, -1.246, -0.033]} rotation={[-Math.PI, -0.011, 0]} scale={[0.067, 0.062, 0.067]} castShadow receiveShadow />
                <mesh name="coit_base" geometry={nodes.coit_base.geometry} material={materials.roof} position={[-0.003, -1.424, 0.018]} scale={0.436} castShadow receiveShadow />
                <mesh name="water" geometry={nodes.water.geometry} material={materials.water} receiveShadow />
                <mesh name="buildings" geometry={nodes.buildings.geometry} material={materials.roof} position={[0.418, -3.521, -0.327]} scale={0.014} castShadow receiveShadow />
                <mesh name="clouds_city" geometry={nodes.clouds_city.geometry} material={nodes.clouds_city.material} position={[-7.612, -2.829, -8.723]} scale={2.122} />
                <mesh name="clouds_city001" geometry={nodes.clouds_city001.geometry} material={nodes.clouds_city001.material} position={[-9.115, -4.332, -6.029]} scale={2.927} />
                <mesh name="clouds_city002" geometry={nodes.clouds_city002.geometry} material={nodes.clouds_city002.material} position={[-8.531, -2.741, -0.397]} rotation={[Math.PI, -1.054, Math.PI]} scale={2.37} />
                <mesh name="clouds_city003" geometry={nodes.clouds_city003.geometry} material={nodes.clouds_city003.material} position={[-10.318, -4.419, -3.343]} rotation={[Math.PI, -1.054, Math.PI]} scale={3.269} />
                <mesh name="clouds_city004" geometry={nodes.clouds_city004.geometry} material={nodes.clouds_city004.material} position={[-9.402, -4.419, 3.037]} rotation={[2.254, -1.211, 2.574]} scale={3.733} />
                <mesh name="clouds_city005" geometry={nodes.clouds_city005.geometry} material={nodes.clouds_city005.material} position={[-10.494, -2.941, 6.399]} rotation={[-0.679, 0.717, 1.26]} scale={2.927} />
                <mesh name="clouds_city006" geometry={nodes.clouds_city006.geometry} material={nodes.clouds_city006.material} position={[-8.942, -2.466, 8.856]} rotation={[1.127, -0.553, 1.003]} scale={3.269} />
                <mesh name="clouds_city007" geometry={nodes.clouds_city007.geometry} material={nodes.clouds_city007.material} position={[-5.509, -4.065, 8.691]} rotation={[-Math.PI, 1.419, -Math.PI]} scale={2.927} />
                <mesh name="clouds_city008" geometry={nodes.clouds_city008.geometry} material={nodes.clouds_city008.material} position={[-0.03, -2.475, 9.712]} rotation={[0, -0.365, 0]} scale={2.37} />
                <mesh name="clouds_city009" geometry={nodes.clouds_city009.geometry} material={nodes.clouds_city009.material} position={[-2.671, -4.153, 9.472]} rotation={[0, -0.365, 0]} scale={3.269} />
                <mesh name="clouds_city010" geometry={nodes.clouds_city010.geometry} material={nodes.clouds_city010.material} position={[3.497, -4.153, 10.052]} rotation={[0.277, -0.078, 0.309]} scale={3.733} />
                <mesh name="clouds_city011" geometry={nodes.clouds_city011.geometry} material={nodes.clouds_city011.material} position={[6.986, -2.675, 9.293]} rotation={[-2.572, 0.501, -2.667]} scale={2.927} />
                <mesh name="clouds_city012" geometry={nodes.clouds_city012.geometry} material={nodes.clouds_city012.material} position={[3.846, -2.482, 11.655]} rotation={[Math.PI, -1.381, Math.PI]} scale={3.502} />
                <mesh name="clouds_city013" geometry={nodes.clouds_city013.geometry} material={nodes.clouds_city013.material} position={[-5.321, -1.646, 12.73]} rotation={[-Math.PI, 0.707, -Math.PI]} scale={2.836} />
                <mesh name="clouds_city014" geometry={nodes.clouds_city014.geometry} material={nodes.clouds_city014.material} position={[-1.455, -2.025, 12.719]} rotation={[-Math.PI, 0.707, -Math.PI]} scale={3.911} />
                <mesh name="clouds_city015" geometry={nodes.clouds_city015.geometry} material={nodes.clouds_city015.material} position={[-13.488, -2.464, 1.112]} rotation={[2.079, 1.472, -2.441]} scale={3.911} />
                <mesh name="clouds_city016" geometry={nodes.clouds_city016.geometry} material={nodes.clouds_city016.material} position={[-14.968, -2.285, 6.69]} rotation={[2.079, 1.472, -2.441]} scale={5.064} />
                <mesh name="clouds_city017" geometry={nodes.clouds_city017.geometry} material={nodes.clouds_city017.material} position={[-10.823, 0.321, 13.329]} rotation={[2.201, 0.963, -2.447]} scale={5.064} />
                <mesh name="clouds_city018" geometry={nodes.clouds_city018.geometry} material={nodes.clouds_city018.material} position={[9.696, -4.49, 7.605]} rotation={[0, -0.365, 0]} scale={2.82} />
                <mesh name="clouds_city019" geometry={nodes.clouds_city019.geometry} material={nodes.clouds_city019.material} position={[9.696, -3.522, 5.476]} rotation={[0.15, 0.029, -0.31]} scale={1.194} />
                <mesh name="clouds_water007" geometry={nodes.clouds_water007.geometry} material={nodes.clouds_water007.material} position={[14.971, -4.018, -3.329]} rotation={[Math.PI, -0.359, Math.PI]} scale={1.642} />
                <mesh name="clouds_water008" geometry={nodes.clouds_water008.geometry} material={nodes.clouds_water008.material} position={[13.553, -3.125, -6.172]} rotation={[0, 1.413, 0]} scale={1.33} />
                <mesh name="clouds_water009" geometry={nodes.clouds_water009.geometry} material={nodes.clouds_water009.material} position={[15.073, -4.067, -4.977]} rotation={[0, 1.413, 0]} scale={1.835} />
                <mesh name="clouds_water010" geometry={nodes.clouds_water010.geometry} material={nodes.clouds_water010.material} position={[13.333, -4.067, -8.148]} rotation={[1.988, 1.267, -1.718]} scale={2.095} />
                <mesh name="clouds_water011" geometry={nodes.clouds_water011.geometry} material={nodes.clouds_water011.material} position={[13.243, -3.238, -10.13]} rotation={[-2.163, -0.964, -1.484]} scale={1.642} />
                <mesh name="clouds_water012" geometry={nodes.clouds_water012.geometry} material={nodes.clouds_water012.material} position={[11.943, -2.971, -11.115]} rotation={[2.172, 0.372, -2.486]} scale={1.835} />
                <mesh name="clouds_water013" geometry={nodes.clouds_water013.geometry} material={nodes.clouds_water013.material} position={[10.172, -3.868, -12.286]} rotation={[0, -1.059, 0]} scale={1.642} />
                <mesh name="clouds_water014" geometry={nodes.clouds_water014.geometry} material={nodes.clouds_water014.material} position={[7.092, -2.976, -14.104]} rotation={[-Math.PI, 0.005, -Math.PI]} scale={1.33} />
                <mesh name="clouds_water015" geometry={nodes.clouds_water015.geometry} material={nodes.clouds_water015.material} position={[8.527, -3.918, -12.614]} rotation={[-Math.PI, 0.005, -Math.PI]} scale={1.835} />
                <mesh name="clouds_water016" geometry={nodes.clouds_water016.geometry} material={nodes.clouds_water016.material} position={[5.173, -3.918, -14.889]} rotation={[2.855, -0.268, -2.932]} scale={2.095} />
                <mesh name="clouds_water001" geometry={nodes.clouds_water001.geometry} material={nodes.clouds_water001.material} position={[2.312, -3.54, -14.979]} rotation={[0, -1.506, 0]} scale={1.781} />
                <mesh name="clouds_water002" geometry={nodes.clouds_water002.geometry} material={nodes.clouds_water002.material} position={[-1.085, -2.572, -14.404]} rotation={[-Math.PI, 0.452, -Math.PI]} scale={1.442} />
                <mesh name="clouds_water003" geometry={nodes.clouds_water003.geometry} material={nodes.clouds_water003.material} position={[0.634, -3.594, -15.604]} rotation={[-Math.PI, 0.452, -Math.PI]} scale={1.989} />
                <mesh name="clouds_water004" geometry={nodes.clouds_water004.geometry} material={nodes.clouds_water004.material} position={[-3.205, -3.594, -14.798]} rotation={[2.861, 0.162, -2.808]} scale={2.272} />
                <mesh name="clouds_water005" geometry={nodes.clouds_water005.geometry} material={nodes.clouds_water005.material} position={[-5.289, -2.694, -15.329]} rotation={[-0.598, -0.574, 0.418]} scale={1.781} />
                <mesh name="clouds_water006" geometry={nodes.clouds_water006.geometry} material={nodes.clouds_water006.material} position={[-6.721, -2.405, -14.29]} rotation={[2.148, -0.41, 2.761]} scale={1.989} />
                <mesh name="clouds_water017" geometry={nodes.clouds_water017.geometry} material={nodes.clouds_water017.material} position={[-8.494, -3.378, -12.821]} rotation={[0, 0.217, 0]} scale={1.781} />
                <mesh name="clouds_water018" geometry={nodes.clouds_water018.geometry} material={nodes.clouds_water018.material} position={[-11.35, -2.41, -10.198]} rotation={[Math.PI, -1.271, Math.PI]} scale={1.442} />
                <mesh name="clouds_water019" geometry={nodes.clouds_water019.geometry} material={nodes.clouds_water019.material} position={[-9.352, -3.432, -11.217]} rotation={[Math.PI, -1.271, Math.PI]} scale={1.989} />
                <mesh name="clouds_water020" geometry={nodes.clouds_water020.geometry} material={nodes.clouds_water020.material} position={[-12.77, -3.432, -8.453]} rotation={[1.628, -1.294, 1.917]} scale={2.272} />
                <mesh name="clouds_water021" geometry={nodes.clouds_water021.geometry} material={nodes.clouds_water021.material} position={[8.942, -3.54, 12.503]} rotation={[-Math.PI, 0.69, -Math.PI]} scale={1.781} />
                <mesh name="clouds_water022" geometry={nodes.clouds_water022.geometry} material={nodes.clouds_water022.material} position={[10.85, -2.572, 9.633]} rotation={[0, 0.364, 0]} scale={1.442} />
                <mesh name="clouds_water023" geometry={nodes.clouds_water023.geometry} material={nodes.clouds_water023.material} position={[10.547, -3.594, 11.708]} rotation={[0, 0.364, 0]} scale={1.989} />
                <mesh name="clouds_water024" geometry={nodes.clouds_water024.geometry} material={nodes.clouds_water024.material} position={[12.589, -3.594, 8.359]} rotation={[0.342, 0.619, 0.084]} scale={2.272} />
                <mesh name="clouds_water025" geometry={nodes.clouds_water025.geometry} material={nodes.clouds_water025.material} position={[14.404, -2.694, 7.204]} rotation={[-2.644, -0.134, -2.297]} scale={1.781} />
                <mesh name="clouds_water026" geometry={nodes.clouds_water026.geometry} material={nodes.clouds_water026.material} position={[14.627, -2.405, 5.45]} rotation={[1.503, 0.692, -1.296]} scale={1.989} />
                <mesh name="clouds_water027" geometry={nodes.clouds_water027.geometry} material={nodes.clouds_water027.material} position={[14.772, -3.378, 3.152]} rotation={[Math.PI, -1.033, Math.PI]} scale={1.781} />
                <mesh name="clouds_water028" geometry={nodes.clouds_water028.geometry} material={nodes.clouds_water028.material} position={[14.818, -2.41, -0.726]} rotation={[-Math.PI, 1.055, -Math.PI]} scale={1.442} />
                <mesh name="clouds_water029" geometry={nodes.clouds_water029.geometry} material={nodes.clouds_water029.material} position={[14.191, -3.432, 1.428]} rotation={[-Math.PI, 1.055, -Math.PI]} scale={1.989} />
                <mesh name="clouds_water" geometry={nodes.clouds_water.geometry} material={nodes.clouds_water.material} position={[14.519, -3.432, -2.956]} rotation={[2.765, 0.735, -2.595]} scale={2.272} />
                <mesh name="clouds_floating" geometry={nodes.clouds_floating.geometry} material={nodes.clouds_floating.material} position={[-3.75, 1.96, -5.366]} rotation={[0, -0.121, 0]} scale={-0.565} castShadow receiveShadow />
                <mesh name="clouds_floating001" geometry={nodes.clouds_floating001.geometry} material={nodes.clouds_floating001.material} position={[-10.553, 2.403, 2.87]} rotation={[0.319, -0.909, 0.214]} scale={-0.87} castShadow receiveShadow />
                <mesh name="clouds_floating002" geometry={nodes.clouds_floating002.geometry} material={nodes.clouds_floating002.material} position={[-5.05, 3.536, 6.087]} rotation={[0.612, 0.433, -3.1]} scale={0.623} castShadow receiveShadow />
                <mesh name="clouds_floating003" geometry={nodes.clouds_floating003.geometry} material={nodes.clouds_floating003.material} position={[11.107, 3.536, 6.087]} rotation={[1.949, 0.974, 1.451]} scale={0.531} castShadow receiveShadow />
                <mesh name="clouds_floating004" geometry={nodes.clouds_floating004.geometry} material={nodes.clouds_floating004.material} position={[12.17, 2.403, -4.747]} rotation={[-2.796, 0.898, 0.68]} scale={-1.058} castShadow receiveShadow />
                <mesh name="clouds_floating005" geometry={nodes.clouds_floating005.geometry} material={nodes.clouds_floating005.material} position={[5.521, 1.96, -10.557]} rotation={[1.775, -0.933, 0.899]} scale={-0.565} castShadow receiveShadow />
                <mesh name="clouds_floating006" geometry={nodes.clouds_floating006.geometry} material={nodes.clouds_floating006.material} position={[-0.162, 3.247, 8.369]} rotation={[-0.227, 0.76, 0.094]} scale={-0.565} castShadow receiveShadow />
                <mesh name="clouds_floating007" geometry={nodes.clouds_floating007.geometry} material={nodes.clouds_floating007.material} position={[19.267, 7.217, 7.928]} rotation={[-Math.PI, 0.053, -Math.PI]} scale={-0.565} castShadow receiveShadow />
                <mesh name="clouds_floating008" geometry={nodes.clouds_floating008.geometry} material={nodes.clouds_floating008.material} position={[25.496, 7.66, -0.749]} rotation={[2.847, 0.845, -2.96]} scale={-0.87} castShadow receiveShadow />
                <mesh name="clouds_floating009" geometry={nodes.clouds_floating009.geometry} material={nodes.clouds_floating009.material} position={[19.788, 8.793, -3.587]} rotation={[2.51, -0.488, -0.002]} scale={0.531} castShadow receiveShadow />
                <mesh name="clouds_floating010" geometry={nodes.clouds_floating010.geometry} material={nodes.clouds_floating010.material} position={[3.088, 8.001, -16.374]} rotation={[2.126, 0.792, -2.466]} scale={0.531} castShadow receiveShadow />
                <mesh name="clouds_floating011" geometry={nodes.clouds_floating011.geometry} material={nodes.clouds_floating011.material} position={[12.277, 9.1, -15.093]} rotation={[1.017, 0.598, -1.152]} scale={-1.058} castShadow receiveShadow />
                <mesh name="clouds_floating012" geometry={nodes.clouds_floating012.geometry} material={nodes.clouds_floating012.material} position={[5.095, 11.282, 13.926]} rotation={[0, -1.375, 0]} scale={-0.565} castShadow receiveShadow />
                <mesh name="clouds_floating013" geometry={nodes.clouds_floating013.geometry} material={nodes.clouds_floating013.material} position={[-4.85, 11.725, 10.029]} rotation={[2.815, -0.928, 2.835]} scale={-0.87} castShadow receiveShadow />
                <mesh name="clouds_floating014" geometry={nodes.clouds_floating014.geometry} material={nodes.clouds_floating014.material} position={[-15.805, 6.103, -3.587]} rotation={[-1.205, -1.098, -0.888]} scale={0.686} castShadow receiveShadow />
                <mesh name="clouds_floating015" geometry={nodes.clouds_floating015.geometry} material={nodes.clouds_floating015.material} position={[-1.726, 6.974, 8.353]} rotation={[1.902, 0.445, -2.146]} scale={-1.058} castShadow receiveShadow />
                <mesh name="clouds_floating016" geometry={nodes.clouds_floating016.geometry} material={nodes.clouds_floating016.material} position={[-6.728, 8.23, 6.534]} rotation={[-1.864, 0.433, -3.1]} scale={0.623} castShadow receiveShadow />
            </group>
        </group>
    )
})

Model.displayName = 'Model'


useGLTF.preload('/3d/north_beach_web.glb')
